### PR TITLE
Some initial corrections

### PR DESCRIPTION
**Pull request by jgharston**

### CODE REVIEW

**Comment by jgharston** [comment]
Some initial corrections.

**Comment by chelsea6502** [comment]
**Holy smokes!** Thank you JG Harston for sweeping through my code with corrections!!! It may take me a couple of days to soak in all the changes before merging.

My target audience is 6502 newbies who are unfamiliar with Acorn or the BBC Micro. I plan to at the very least add definitions alongside the Acorn lingo such as 'MOS', 'Language', and 'API'

**Comment by chelsea6502** [comment]
I've created a branch called 'jgharston' to go through your changes. I've also invited you to collaborator access in case you would like to work directly in that branch instead of forking.

**Comment by chelsea6502** [comment]
Thanks JGHarston! Sorry to hear about the 'lurgi'. No need to explain why you were away. It's all volunteer work after all!

I knew about Mini65 before, but I didn't know about the BenEater one! I'll take a look at the build options and see if I can get it to run.

Thank you again! Just sent another contributor request email.

**Pull request merged**
